institute: "University of Hamburg <br> Research Training Group Collective Decision-Making"
author: "Jasmin Sarah KÃ¶nig & Tilko Swalve"
footer: "Workshop Collective Decision-Making"
format:
  revealjs:
    theme: slides.scss
    transition: fade
    slide-number: true
    chalkboard: false
    controls: true
editor: visual
execute:
  freeze: auto
  echo: true